/* ============
 * Mutation types for the project module
 * ============
 *
 * The mutation types that are available
 * on the project module.
 */

export const FIND = 'FIND';
export const MEASUREMENT = 'MEASUREMENT';
export const ADD_NEW_ESTIMATE_LINE = 'ADD_NEW_ESTIMATE_LINE';
export const UPDATE_ESTIMATE_LINE = 'UPDATE_ESTIMATE_LINE';
export const CALCULATE_CONSTRUCTION_CHECK = 'CALCULATE_CONSTRUCTION_CHECK';
export const SET_CONSTRUCTION_CHECK = 'SET_CONSTRUCTION_CHECK';
export const REMOVE_CONSTRUCTION_LINE = 'REMOVE_CONSTRUCTION_LINE';
export const INITIATE_ESTIMATE_LINE = 'INITIATE_ESTIMATE_LINE';
export const ALL_MASTER_CODES = 'ALL_MASTER_CODES';
export const SET_SUB_PROJECT_ID = 'SET_SUB_PROJECT_ID';
export const SET_SUB_PROJECT_BUDGET = 'SET_SUB_PROJECT_BUDGET';

export default {
    FIND,
    MEASUREMENT,
    ADD_NEW_ESTIMATE_LINE,
    UPDATE_ESTIMATE_LINE,
    CALCULATE_CONSTRUCTION_CHECK,
    SET_CONSTRUCTION_CHECK,
    REMOVE_CONSTRUCTION_LINE,
    INITIATE_ESTIMATE_LINE,
    ALL_MASTER_CODES,
    SET_SUB_PROJECT_ID,
    SET_SUB_PROJECT_BUDGET,
};
